[package]
name = "deepcompare-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-nn.workspace = true
encoding_rs.workspace = true
rayon.workspace = true
similar.workspace = true
tokenizers.workspace = true

[dev-dependencies]
serde_json = "1"
